var moocsIndicatorsArray = {
  indicatorsDepartments: [
    {
      "department_codes": "CSD",
      "all_the_time_courses": 16,
      "all_the_time_porcent_total_courses": 0.17,
      "all_the_time_registrations": 155263,
      "all_the_time_porcent_total_registrations": 0.11,
      "all_the_time_registrations_from_LAC": 135176,
      "all_the_time_porcent_total_LAC": 0.87,
      "2018_courses": 2,
      "porcent_total_courses": 0.08,
      "2017_2018_courses": -3,
      "2018_registrations": 9875,
      "porcent_total_registrations": 0.04,
      "LAC_Registrations": 8705,
      "porcent_total_LAC": 0.88
    },
    {
      "department_codes": "IFD",
      "all_the_time_courses": 19,
      "all_the_time_porcent_total_courses": 0.21,
      "all_the_time_registrations": 163188,
      "all_the_time_porcent_total_registrations": 0.12,
      "all_the_time_registrations_from_LAC": 141773,
      "all_the_time_porcent_total_LAC": 0.87,
      "2018_courses": 5,
      "porcent_total_courses": 0.19,
      "2017_2018_courses": 1,
      "2018_registrations": 34713,
      "porcent_total_registrations": 0.15,
      "LAC_Registrations": 32195,
      "porcent_total_LAC": 0.93
    },
    {
      "department_codes": "INE",
      "all_the_time_courses": 14,
      "all_the_time_porcent_total_courses": 0.15,
      "all_the_time_registrations": 103810,
      "all_the_time_porcent_total_registrations": 0.07,
      "all_the_time_registrations_from_LAC": 94060,
      "all_the_time_porcent_total_LAC": 0.91,
      "2018_courses": 2,
      "porcent_total_courses": 0.08,
      "2017_2018_courses": -3,
      "2018_registrations": 10714,
      "porcent_total_registrations": 0.04,
      "LAC_Registrations": 9785,
      "porcent_total_LAC": 0.91
    },
    {
      "department_codes": "INT",
      "all_the_time_courses": 6,
      "all_the_time_porcent_total_courses": 0.07,
      "all_the_time_registrations": 53680,
      "all_the_time_porcent_total_registrations": 0.04,
      "all_the_time_registrations_from_LAC": 47799,
      "all_the_time_porcent_total_LAC": 0.89,
      "2018_courses": 3,
      "porcent_total_courses": 0.12,
      "2017_2018_courses": 2,
      "2018_registrations": 23874,
      "porcent_total_registrations": 0.1,
      "LAC_Registrations": 22349,
      "porcent_total_LAC": 0.94
    },
    {
      "department_codes": "KIC",
      "all_the_time_courses": 29,
      "all_the_time_porcent_total_courses": 0.32,
      "all_the_time_registrations": 478012,
      "all_the_time_porcent_total_registrations": 0.34,
      "all_the_time_registrations_from_LAC": 395003,
      "all_the_time_porcent_total_LAC": 0.83,
      "2018_courses": 8,
      "porcent_total_courses": 0.31,
      "2017_2018_courses": -5,
      "2018_registrations": 114352,
      "porcent_total_registrations": 0.48,
      "LAC_Registrations": 88616,
      "porcent_total_LAC": 0.77
    },
    {
      "department_codes": "MIF",
      "all_the_time_courses": 6,
      "all_the_time_porcent_total_courses": 0.07,
      "all_the_time_registrations": 45028,
      "all_the_time_porcent_total_registrations": 0.03,
      "all_the_time_registrations_from_LAC": 40445,
      "all_the_time_porcent_total_LAC": 0.9,
      "2018_courses": 0,
      "porcent_total_courses": 0,
      "2017_2018_courses": -2,
      "2018_registrations": 0,
      "porcent_total_registrations": 0,
      "LAC_Registrations": 0,
      "porcent_total_LAC": 0
    },
    {
      "department_codes": "PRE",
      "all_the_time_courses": 3,
      "all_the_time_porcent_total_courses": 0.03,
      "all_the_time_registrations": 28175,
      "all_the_time_porcent_total_registrations": 0.02,
      "all_the_time_registrations_from_LAC": 25433,
      "all_the_time_porcent_total_LAC": 0.9,
      "2018_courses": 2,
      "porcent_total_courses": 0.08,
      "2017_2018_courses": 2,
      "2018_registrations": 12750,
      "porcent_total_registrations": 0.05,
      "LAC_Registrations": 11418,
      "porcent_total_LAC": 0.9
    },
    {
      "department_codes": "RES",
      "all_the_time_courses": 6,
      "all_the_time_porcent_total_courses": 0.07,
      "all_the_time_registrations": 51967,
      "all_the_time_porcent_total_registrations": 0.04,
      "all_the_time_registrations_from_LAC": 44551,
      "all_the_time_porcent_total_LAC": 0.86,
      "2018_courses": 2,
      "porcent_total_courses": 0.08,
      "2017_2018_courses": 0,
      "2018_registrations": 14213,
      "porcent_total_registrations": 0.06,
      "LAC_Registrations": 12344,
      "porcent_total_LAC": 0.87
    },
    {
      "department_codes": "SCL",
      "all_the_time_courses": 23,
      "all_the_time_porcent_total_courses": 0.25,
      "all_the_time_registrations": 180856,
      "all_the_time_porcent_total_registrations": 0.13,
      "all_the_time_registrations_from_LAC": 132884,
      "all_the_time_porcent_total_LAC": 0.87,
      "2018_courses": 6,
      "porcent_total_courses": 0.23,
      "2017_2018_courses": -3,
      "2018_registrations": 52977,
      "porcent_total_registrations": 0.18,
      "LAC_Registrations": 46538,
      "porcent_total_LAC": 0.88
    },
    {
      "department_codes": "VPC",
      "all_the_time_courses": 10,
      "all_the_time_porcent_total_courses": 0.11,
      "all_the_time_registrations": 107091,
      "all_the_time_porcent_total_registrations": 0.08,
      "all_the_time_registrations_from_LAC": 88843,
      "all_the_time_porcent_total_LAC": 0.83,
      "2018_courses": 3,
      "porcent_total_courses": 0.12,
      "2017_2018_courses": -2,
      "2018_registrations": 26547,
      "porcent_total_registrations": 0.11,
      "LAC_Registrations": 21274,
      "porcent_total_LAC": 0.8
    }
  ],
  indicatorsDivisions: [
    {
      "division_codes": "EDU",
      "all_the_time_courses": 7,
      "all_the_time_porcent_total_courses": 0.08,
      "all_the_time_registrations": 39914,
      "all_the_time_porcent_total_registrations": 0.03,
      "all_the_time_registrations_from_LAC": 31873,
      "all_the_time_porcent_total_LAC": 0.8,
      "2018_courses": 4,
      "porcent_total_courses": 0.15,
      "2017_2018_courses": 1,
      "2018_registrations": 22983,
      "porcent_total_registrations": 0.1,
      "LAC_Registrations": 18666,
      "porcent_total_LAC": 0.81
    },
    {
      "division_codes": "FMM",
      "all_the_time_courses": 10,
      "all_the_time_porcent_total_courses": 0.11,
      "all_the_time_registrations": 70616,
      "all_the_time_porcent_total_registrations": 0.05,
      "all_the_time_registrations_from_LAC": 64433,
      "all_the_time_porcent_total_LAC": 0.91,
      "2018_courses": 2,
      "porcent_total_courses": 0.08,
      "2017_2018_courses": -1,
      "2018_registrations": 13219,
      "porcent_total_registrations": 0.06,
      "LAC_Registrations": 12537,
      "porcent_total_LAC": 0.95
    },
    {
      "division_codes": "HUD",
      "all_the_time_courses": 10,
      "all_the_time_porcent_total_courses": 0.11,
      "all_the_time_registrations": 119385,
      "all_the_time_porcent_total_registrations": 0.08,
      "all_the_time_registrations_from_LAC": 106426,
      "all_the_time_porcent_total_LAC": 0.89,
      "2018_courses": 0,
      "porcent_total_courses": 0,
      "2017_2018_courses": -3,
      "2018_registrations": 0,
      "porcent_total_registrations": 0,
      "LAC_Registrations": 0,
      "porcent_total_LAC": 0
    },
    {
      "division_codes": "ICS",
      "all_the_time_courses": 6,
      "all_the_time_porcent_total_courses": 0.07,
      "all_the_time_registrations": 64397,
      "all_the_time_porcent_total_registrations": 0.05,
      "all_the_time_registrations_from_LAC": 51907,
      "all_the_time_porcent_total_LAC": 0.81,
      "2018_courses": 1,
      "porcent_total_courses": 0.04,
      "2017_2018_courses": 0,
      "2018_registrations": 8744,
      "porcent_total_registrations": 0.04,
      "LAC_Registrations": 8240,
      "porcent_total_LAC": 0.94
    },
    {
      "division_codes": "IFD Front Desk",
      "all_the_time_courses": 3,
      "all_the_time_porcent_total_courses": 0.03,
      "all_the_time_registrations": 28175,
      "all_the_time_porcent_total_registrations": 0.02,
      "all_the_time_registrations_from_LAC": 25433,
      "all_the_time_porcent_total_LAC": 0.9,
      "2018_courses": 2,
      "porcent_total_courses": 0.08,
      "2017_2018_courses": 2,
      "2018_registrations": 12750,
      "porcent_total_registrations": 0.05,
      "LAC_Registrations": 11418,
      "porcent_total_LAC": 0.9
    },
    {
      "division_codes": "INE Front Desk",
      "all_the_time_courses": 8,
      "all_the_time_porcent_total_courses": 0.09,
      "all_the_time_registrations": 57373,
      "all_the_time_porcent_total_registrations": 0.04,
      "all_the_time_registrations_from_LAC": 51874,
      "all_the_time_porcent_total_LAC": 0.9,
      "2018_courses": 0,
      "porcent_total_courses": 0,
      "2017_2018_courses": -3,
      "2018_registrations": 0,
      "porcent_total_registrations": 0,
      "LAC_Registrations": 0,
      "porcent_total_LAC": 0
    },
    {
      "division_codes": "INT",
      "all_the_time_courses": 6,
      "all_the_time_porcent_total_courses": 0.07,
      "all_the_time_registrations": 53680,
      "all_the_time_porcent_total_registrations": 0.04,
      "all_the_time_registrations_from_LAC": 47799,
      "all_the_time_porcent_total_LAC": 0.89,
      "2018_courses": 3,
      "porcent_total_courses": 0.12,
      "2017_2018_courses": 2,
      "2018_registrations": 23874,
      "porcent_total_registrations": 0.1,
      "LAC_Registrations": 22349,
      "porcent_total_LAC": 0.94
    },
    {
      "division_codes": "KLD",
      "all_the_time_courses": 29,
      "all_the_time_porcent_total_courses": 0.32,
      "all_the_time_registrations": 478012,
      "all_the_time_porcent_total_registrations": 0.34,
      "all_the_time_registrations_from_LAC": 395003,
      "all_the_time_porcent_total_LAC": 0.83,
      "2018_courses": 8,
      "porcent_total_courses": 0.31,
      "2017_2018_courses": -5,
      "2018_registrations": 114352,
      "porcent_total_registrations": 0.48,
      "LAC_Registrations": 88616,
      "porcent_total_LAC": 0.77
    },
    {
      "division_codes": "LMK",
      "all_the_time_courses": 5,
      "all_the_time_porcent_total_courses": 0.05,
      "all_the_time_registrations": 25048,
      "all_the_time_porcent_total_registrations": 0.02,
      "all_the_time_registrations_from_LAC": 19938,
      "all_the_time_porcent_total_LAC": 0.8,
      "2018_courses": 1,
      "porcent_total_courses": 0.04,
      "2017_2018_courses": -1,
      "2018_registrations": 5638,
      "porcent_total_registrations": 0.02,
      "LAC_Registrations": 4890,
      "porcent_total_LAC": 0.87
    },
    {
      "division_codes": "MIF",
      "all_the_time_courses": 6,
      "all_the_time_porcent_total_courses": 0.07,
      "all_the_time_registrations": 45028,
      "all_the_time_porcent_total_registrations": 0.03,
      "all_the_time_registrations_from_LAC": 40445,
      "all_the_time_porcent_total_LAC": 0.9,
      "2018_courses": 0,
      "porcent_total_courses": 0,
      "2017_2018_courses": -2,
      "2018_registrations": 0,
      "porcent_total_registrations": 0,
      "LAC_Registrations": 0,
      "porcent_total_LAC": 0
    },
    {
      "division_codes": "PCY",
      "all_the_time_courses": 3,
      "all_the_time_porcent_total_courses": 0.03,
      "all_the_time_registrations": 28175,
      "all_the_time_porcent_total_registrations": 0.02,
      "all_the_time_registrations_from_LAC": 25433,
      "all_the_time_porcent_total_LAC": 0.9,
      "2018_courses": 2,
      "porcent_total_courses": 0.08,
      "2017_2018_courses": 2,
      "2018_registrations": 12750,
      "porcent_total_registrations": 0.05,
      "LAC_Registrations": 11418,
      "porcent_total_LAC": 0.9
    },
    {
      "division_codes": "RES",
      "all_the_time_courses": 6,
      "all_the_time_porcent_total_courses": 0.07,
      "all_the_time_registrations": 51967,
      "all_the_time_porcent_total_registrations": 0.04,
      "all_the_time_registrations_from_LAC": 44551,
      "all_the_time_porcent_total_LAC": 0.86,
      "2018_courses": 2,
      "porcent_total_courses": 0.08,
      "2017_2018_courses": 0,
      "2018_registrations": 14213,
      "porcent_total_registrations": 0.06,
      "LAC_Registrations": 12344,
      "porcent_total_LAC": 0.87
    },
    {
      "division_codes": "RND",
      "all_the_time_courses": 6,
      "all_the_time_porcent_total_courses": 0.07,
      "all_the_time_registrations": 35878,
      "all_the_time_porcent_total_registrations": 0.03,
      "all_the_time_registrations_from_LAC": 28750,
      "all_the_time_porcent_total_LAC": 0.8,
      "2018_courses": 2,
      "porcent_total_courses": 0.08,
      "2017_2018_courses": 0,
      "2018_registrations": 9875,
      "porcent_total_registrations": 0.04,
      "LAC_Registrations": 8705,
      "porcent_total_LAC": 0.88
    },
    {
      "division_codes": "SPH",
      "all_the_time_courses": 15,
      "all_the_time_porcent_total_courses": 0.16,
      "all_the_time_registrations": 115894,
      "all_the_time_porcent_total_registrations": 0.08,
      "all_the_time_registrations_from_LAC": 106159,
      "all_the_time_porcent_total_LAC": 0.92,
      "2018_courses": 3,
      "porcent_total_courses": 0.12,
      "2017_2018_courses": -3,
      "2018_registrations": 24356,
      "porcent_total_registrations": 0.1,
      "LAC_Registrations": 22982,
      "porcent_total_LAC": 0.94
    },
    {
      "division_codes": "TSP",
      "all_the_time_courses": 2,
      "all_the_time_porcent_total_courses": 0.02,
      "all_the_time_registrations": 12101,
      "all_the_time_porcent_total_registrations": 0.01,
      "all_the_time_registrations_from_LAC": 11383,
      "all_the_time_porcent_total_LAC": 0.94,
      "2018_courses": 1,
      "porcent_total_courses": 0.04,
      "2017_2018_courses": 0,
      "2018_registrations": 5454,
      "porcent_total_registrations": 0.02,
      "LAC_Registrations": 5068,
      "porcent_total_LAC": 0.93
    },
    {
      "division_codes": "VPC Front Desk",
      "all_the_time_courses": 10,
      "all_the_time_porcent_total_courses": 0.11,
      "all_the_time_registrations": 107091,
      "all_the_time_porcent_total_registrations": 0.08,
      "all_the_time_registrations_from_LAC": 88843,
      "all_the_time_porcent_total_LAC": 0.83,
      "2018_courses": 3,
      "porcent_total_courses": 0.12,
      "2017_2018_courses": -2,
      "2018_registrations": 26547,
      "porcent_total_registrations": 0.11,
      "LAC_Registrations": 21274,
      "porcent_total_LAC": 0.8
    },
    {
      "division_codes": "WSA",
      "all_the_time_courses": 4,
      "all_the_time_porcent_total_courses": 0.04,
      "all_the_time_registrations": 34336,
      "all_the_time_porcent_total_registrations": 0.02,
      "all_the_time_registrations_from_LAC": 30803,
      "all_the_time_porcent_total_LAC": 0.9,
      "2018_courses": 1,
      "porcent_total_courses": 0.04,
      "2017_2018_courses": 0,
      "2018_registrations": 5260,
      "porcent_total_registrations": 0.02,
      "LAC_Registrations": 4717,
      "porcent_total_LAC": 0.9
    }
  ],
  indicatorsIDB: [
    {
      "all_the_time_courses": 92,
      "all_the_time_porcent_total_courses": 1,
      "all_the_time_registrations": 1009520,
      "all_the_time_porcent_total_registrations": 1,
      "all_the_time_registrations_from_LAC": 857526,
      "all_the_time_porcent_total_LAC": 0.85,
      "2018_courses": 26,
      "porcent_total_courses": 1,
      "2017_2018_courses": -5,
      "2018_registrations": 238166,
      "porcent_total_registrations": 1,
      "LAC_Registrations": 200972,
      "porcent_total_LAC": 0.84
    }
  ]
};

var moocsGaugesIndicators = {
  indicatorsDepartmentsAllTheTime: [{
      "departmentCode": "CSD",
      "courses": 16,
      "percentageCourses": 17.39,
      "registrations": 155263,
      "percentageRegistrations": 11.03,
      "LAC": 135176,
      "percentageLAC": 87.06
    },
    {
      "departmentCode": "IFD",
      "courses": 19,
      "percentageCourses": 20.65,
      "registrations": 163188,
      "percentageRegistrations": 11.6,
      "LAC": 141773,
      "percentageLAC": 86.88
    },
    {
      "departmentCode": "INE",
      "courses": 14,
      "percentageCourses": 15.22,
      "registrations": 103810,
      "percentageRegistrations": 7.38,
      "LAC": 94060,
      "percentageLAC": 90.61
    },
    {
      "departmentCode": "INT",
      "courses": 6,
      "percentageCourses": 6.52,
      "registrations": 53680,
      "percentageRegistrations": 3.82,
      "LAC": 47799,
      "percentageLAC": 89.04
    },
    {
      "departmentCode": "KIC",
      "courses": 29,
      "percentageCourses": 31.52,
      "registrations": 478012,
      "percentageRegistrations": 33.97,
      "LAC": 395003,
      "percentageLAC": 82.63
    },
    {
      "departmentCode": "MIF",
      "courses": 6,
      "percentageCourses": 6.52,
      "registrations": 45028,
      "percentageRegistrations": 3.2,
      "LAC": 40445,
      "percentageLAC": 89.82
    },
    {
      "departmentCode": "PRE",
      "courses": 3,
      "percentageCourses": 3.26,
      "registrations": 28175,
      "percentageRegistrations": 2,
      "LAC": 25433,
      "percentageLAC": 90.27
    },
    {
      "departmentCode": "RES",
      "courses": 6,
      "percentageCourses": 6.52,
      "registrations": 51967,
      "percentageRegistrations": 3.69,
      "LAC": 44551,
      "percentageLAC": 85.73
    },
    {
      "departmentCode": "SCL",
      "courses": 23,
      "percentageCourses": 25,
      "registrations": 180856,
      "percentageRegistrations": 12.85,
      "LAC": 132884,
      "percentageLAC": 87.18
    },
    {
      "departmentCode": "VPC",
      "courses": 10,
      "percentageCourses": 10.87,
      "registrations": 107091,
      "percentageRegistrations": 7.61,
      "LAC": 88843,
      "percentageLAC": 82.96
    }
  ],
  indicatorsDepartments2018: [{
      "departmentCode": "CSD",
      "courses": 2,
      "percentageCourses": 7.69,
      "registrations": 9875,
      "percentageRegistrations": 4.15,
      "LAC": 8705,
      "percentageLAC": 88.15
    },
    {
      "departmentCode": "IFD",
      "courses": 5,
      "percentageCourses": 19.23,
      "registrations": 34713,
      "percentageRegistrations": 14.58,
      "LAC": 32195,
      "percentageLAC": 92.75
    },
    {
      "departmentCode": "INE",
      "courses": 2,
      "percentageCourses": 7.69,
      "registrations": 10714,
      "percentageRegistrations": 4.5,
      "LAC": 9785,
      "percentageLAC": 91.33
    },
    {
      "departmentCode": "INT",
      "courses": 3,
      "percentageCourses": 11.54,
      "registrations": 23874,
      "percentageRegistrations": 10.02,
      "LAC": 22349,
      "percentageLAC": 93.61
    },
    {
      "departmentCode": "KIC",
      "courses": 8,
      "percentageCourses": 30.77,
      "registrations": 114352,
      "percentageRegistrations": 48.01,
      "LAC": 88616,
      "percentageLAC": 77.49
    },
    {
      "departmentCode": "MIF",
      "courses": 0,
      "percentageCourses": 0,
      "registrations": 0,
      "percentageRegistrations": 0,
      "LAC": 0,
      "percentageLAC": 0
    },
    {
      "departmentCode": "PRE",
      "courses": 2,
      "percentageCourses": 7.69,
      "registrations": 12750,
      "percentageRegistrations": 5.35,
      "LAC": 11418,
      "percentageLAC": 89.55
    },
    {
      "departmentCode": "RES",
      "courses": 2,
      "percentageCourses": 7.69,
      "registrations": 14213,
      "percentageRegistrations": 5.97,
      "LAC": 12344,
      "percentageLAC": 86.85
    },
    {
      "departmentCode": "SCL",
      "courses": 6,
      "percentageCourses": 23.08,
      "registrations": 52977,
      "percentageRegistrations": 17.51,
      "LAC": 46538,
      "percentageLAC": 88.15
    },
    {
      "departmentCode": "VPC",
      "courses": 3,
      "percentageCourses": 11.54,
      "registrations": 26547,
      "percentageRegistrations": 11.15,
      "LAC": 21274,
      "percentageLAC": 80.14
    }
  ],
  indicatorsDivisions2018: [{
      "divisionCode": "EDU",
      "courses": 4,
      "percentageCourses": 15.38,
      "registrations": 22983,
      "percentageRegistrations": 9.65,
      "LAC": 18666,
      "percentageLAC": 81.22
    },
    {
      "divisionCode": "FMM",
      "courses": 2,
      "percentageCourses": 7.69,
      "registrations": 13219,
      "percentageRegistrations": 5.55,
      "LAC": 12537,
      "percentageLAC": 94.84
    },
    {
      "divisionCode": "HUD",
      "courses": 0,
      "percentageCourses": 0,
      "registrations": 0,
      "percentageRegistrations": 0,
      "LAC": 0,
      "percentageLAC": 0
    },
    {
      "divisionCode": "ICS",
      "courses": 1,
      "percentageCourses": 3.85,
      "registrations": 8744,
      "percentageRegistrations": 3.67,
      "LAC": 8240,
      "percentageLAC": 94.24
    },
    {
      "divisionCode": "IFD",
      "courses": 2,
      "percentageCourses": 7.69,
      "registrations": 12750,
      "percentageRegistrations": 5.35,
      "LAC": 11418,
      "percentageLAC": 89.55
    },
    {
      "divisionCode": "INE",
      "courses": 0,
      "percentageCourses": 0,
      "registrations": 0,
      "percentageRegistrations": 0,
      "LAC": 0,
      "percentageLAC": 0
    },
    {
      "divisionCode": "INT",
      "courses": 3,
      "percentageCourses": 11.54,
      "registrations": 23874,
      "percentageRegistrations": 10.02,
      "LAC": 22349,
      "percentageLAC": 93.61
    },
    {
      "divisionCode": "KLD",
      "courses": 8,
      "percentageCourses": 30.77,
      "registrations": 114352,
      "percentageRegistrations": 48.01,
      "LAC": 88616,
      "percentageLAC": 77.49
    },
    {
      "divisionCode": "LMK",
      "courses": 1,
      "percentageCourses": 3.85,
      "registrations": 5638,
      "percentageRegistrations": 2.37,
      "LAC": 4890,
      "percentageLAC": 86.73
    },
    {
      "divisionCode": "MIF",
      "courses": 0,
      "percentageCourses": 0,
      "registrations": 0,
      "percentageRegistrations": 0,
      "LAC": 0,
      "percentageLAC": 0
    },
    {
      "divisionCode": "PCY",
      "courses": 2,
      "percentageCourses": 7.69,
      "registrations": 12750,
      "percentageRegistrations": 5.35,
      "LAC": 11418,
      "percentageLAC": 89.55
    },
    {
      "divisionCode": "RES",
      "courses": 2,
      "percentageCourses": 7.69,
      "registrations": 14213,
      "percentageRegistrations": 5.97,
      "LAC": 12344,
      "percentageLAC": 86.85
    },
    {
      "divisionCode": "RND",
      "courses": 2,
      "percentageCourses": 7.69,
      "registrations": 9875,
      "percentageRegistrations": 4.15,
      "LAC": 8705,
      "percentageLAC": 88.15
    },
    {
      "divisionCode": "SPH",
      "courses": 3,
      "percentageCourses": 11.54,
      "registrations": 24356,
      "percentageRegistrations": 10.23,
      "LAC": 22982,
      "percentageLAC": 94.36
    },
    {
      "divisionCode": "TSP",
      "courses": 1,
      "percentageCourses": 3.85,
      "registrations": 5454,
      "percentageRegistrations": 2.29,
      "LAC": 5068,
      "percentageLAC": 92.92
    },
    {
      "divisionCode": "VPC",
      "courses": 3,
      "percentageCourses": 11.54,
      "registrations": 26547,
      "percentageRegistrations": 11.15,
      "LAC": 21274,
      "percentageLAC": 80.14
    },
    {
      "divisionCode": "WSA",
      "courses": 1,
      "percentageCourses": 3.85,
      "registrations": 5260,
      "percentageRegistrations": 2.21,
      "LAC": 4717,
      "percentageLAC": 89.68
    }
  ],
  indicatorsDivisionsAllTheTime: [{
      "divisionCode": "EDU",
      "courses": 7,
      "percentageCourses": 7.61,
      "registrations": 39914,
      "percentageRegistrations": 2.84,
      "LAC": 31873,
      "percentageLAC": 79.85
    },
    {
      "divisionCode": "FMM",
      "courses": 10,
      "percentageCourses": 10.87,
      "registrations": 70616,
      "percentageRegistrations": 5.02,
      "LAC": 64433,
      "percentageLAC": 91.24
    },
    {
      "divisionCode": "HUD",
      "courses": 10,
      "percentageCourses": 10.87,
      "registrations": 119385,
      "percentageRegistrations": 8.48,
      "LAC": 106426,
      "percentageLAC": 89.15
    },
    {
      "divisionCode": "ICS",
      "courses": 6,
      "percentageCourses": 6.52,
      "registrations": 64397,
      "percentageRegistrations": 4.58,
      "LAC": 51907,
      "percentageLAC": 80.6
    },
    {
      "divisionCode": "IFD Front Desk",
      "courses": 3,
      "percentageCourses": 3.26,
      "registrations": 28175,
      "percentageRegistrations": 2,
      "LAC": 25433,
      "percentageLAC": 90.27
    },
    {
      "divisionCode": "INE Front Desk",
      "courses": 8,
      "percentageCourses": 8.7,
      "registrations": 57373,
      "percentageRegistrations": 4.08,
      "LAC": 51874,
      "percentageLAC": 90.42
    },
    {
      "divisionCode": "INT",
      "courses": 6,
      "percentageCourses": 6.52,
      "registrations": 53680,
      "percentageRegistrations": 3.82,
      "LAC": 47799,
      "percentageLAC": 89.04
    },
    {
      "divisionCode": "KLD",
      "courses": 29,
      "percentageCourses": 31.52,
      "registrations": 478012,
      "percentageRegistrations": 33.97,
      "LAC": 395003,
      "percentageLAC": 82.63
    },
    {
      "divisionCode": "LMK",
      "courses": 5,
      "percentageCourses": 5.43,
      "registrations": 25048,
      "percentageRegistrations": 1.78,
      "LAC": 19938,
      "percentageLAC": 79.6
    },
    {
      "divisionCode": "MIF",
      "courses": 6,
      "percentageCourses": 6.52,
      "registrations": 45028,
      "percentageRegistrations": 3.2,
      "LAC": 40445,
      "percentageLAC": 89.82
    },
    {
      "divisionCode": "PCY",
      "courses": 3,
      "percentageCourses": 3.26,
      "registrations": 28175,
      "percentageRegistrations": 2,
      "LAC": 25433,
      "percentageLAC": 90.27
    },
    {
      "divisionCode": "RES",
      "courses": 6,
      "percentageCourses": 6.52,
      "registrations": 51967,
      "percentageRegistrations": 3.69,
      "LAC": 44551,
      "percentageLAC": 85.73
    },
    {
      "divisionCode": "RND",
      "courses": 6,
      "percentageCourses": 6.52,
      "registrations": 35878,
      "percentageRegistrations": 2.55,
      "LAC": 28750,
      "percentageLAC": 80.13
    },
    {
      "divisionCode": "SPH",
      "courses": 15,
      "percentageCourses": 16.3,
      "registrations": 115894,
      "percentageRegistrations": 8.24,
      "LAC": 106159,
      "percentageLAC": 91.6
    },
    {
      "divisionCode": "TSP",
      "courses": 2,
      "percentageCourses": 2.17,
      "registrations": 12101,
      "percentageRegistrations": 0.86,
      "LAC": 11383,
      "percentageLAC": 94.07
    },
    {
      "divisionCode": "VPC Front Desk",
      "courses": 10,
      "percentageCourses": 10.87,
      "registrations": 107091,
      "percentageRegistrations": 7.61,
      "LAC": 88843,
      "percentageLAC": 82.96
    },
    {
      "divisionCode": "WSA",
      "courses": 4,
      "percentageCourses": 4.35,
      "registrations": 34336,
      "percentageRegistrations": 2.44,
      "LAC": 30803,
      "percentageLAC": 89.71
    }
  ],
  indicatorsIDBAllTheTime: [{
    "courses": 92,
    "percentageCourses": 100,
    "registrations": 1009520,
    "percentageRegistrations": 100,
    "LAC": 857526,
    "percentageLAC": 84.94
  }],
  indicatorsIDB2018: [{
    "courses": 26,
    "percentageCourses": 100,
    "registrations": 238166,
    "percentageRegistrations": 100,
    "LAC": 200972,
    "percentageLAC": 84.38
  }],
}