var bnPublicationsArrays = {
    publicationsDepartments: [
        {
          "department_codes": "AUG",
          "all_the_time_publications": 1,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "141",
          "all_the_time_porcent_total_downloads": 0,
          "all_the_time_LAC_downloads": "32",
          "all_the_time_porcent_total_LAC_downloads": "0.23",
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "department_codes": "BOG",
          "all_the_time_publications": 4,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "1085",
          "all_the_time_porcent_total_downloads": 0,
          "all_the_time_LAC_downloads": "172",
          "all_the_time_porcent_total_LAC_downloads": "0.16",
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "department_codes": "CAN",
          "all_the_time_publications": 67,
          "all_the_time_porcent_total_publications": 0.01,
          "all_the_time_downloads": "180548",
          "all_the_time_porcent_total_downloads": 0.01,
          "all_the_time_LAC_downloads": "136425",
          "all_the_time_porcent_total_LAC_downloads": "0.76",
          "2018_publications": "16",
          "2018_porcent_total_publications": "0.03",
          "2017_2018_publications": "+12",
          "2018_downloads": "33609",
          "2018_porcent_total_downloads": 0.03,
          "2018_LAC_downloads": 25888,
          "2018_porcent_total_LAC_downloads": "0.77"
        },
        {
          "department_codes": "CCB",
          "all_the_time_publications": 153,
          "all_the_time_porcent_total_publications": 0.01,
          "all_the_time_downloads": "236840",
          "all_the_time_porcent_total_downloads": 0.02,
          "all_the_time_LAC_downloads": "106524",
          "all_the_time_porcent_total_LAC_downloads": "0.45",
          "2018_publications": "32",
          "2018_porcent_total_publications": "0.06",
          "2017_2018_publications": "+7",
          "2018_downloads": "12777",
          "2018_porcent_total_downloads": 0.01,
          "2018_LAC_downloads": 5787,
          "2018_porcent_total_LAC_downloads": "0.45"
        },
        {
          "department_codes": "CID",
          "all_the_time_publications": 104,
          "all_the_time_porcent_total_publications": 0.01,
          "all_the_time_downloads": "142861",
          "all_the_time_porcent_total_downloads": 0.01,
          "all_the_time_LAC_downloads": "93962",
          "all_the_time_porcent_total_LAC_downloads": "0.66",
          "2018_publications": "22",
          "2018_porcent_total_publications": "0.04",
          "2017_2018_publications": "+11",
          "2018_downloads": "17747",
          "2018_porcent_total_downloads": 0.02,
          "2018_LAC_downloads": 14078,
          "2018_porcent_total_LAC_downloads": "0.79"
        },
        {
          "department_codes": "CSC",
          "all_the_time_publications": 54,
          "all_the_time_porcent_total_publications": 0.01,
          "all_the_time_downloads": "38631",
          "all_the_time_porcent_total_downloads": 0,
          "all_the_time_LAC_downloads": "26268",
          "all_the_time_porcent_total_LAC_downloads": "0.68",
          "2018_publications": "13",
          "2018_porcent_total_publications": "0.02",
          "2017_2018_publications": "+13",
          "2018_downloads": "3010",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_downloads": 1425,
          "2018_porcent_total_LAC_downloads": "0.47"
        },
        {
          "department_codes": "CSD",
          "all_the_time_publications": 249,
          "all_the_time_porcent_total_publications": 0.02,
          "all_the_time_downloads": "558966",
          "all_the_time_porcent_total_downloads": 0.04,
          "all_the_time_LAC_downloads": "384720",
          "all_the_time_porcent_total_LAC_downloads": "0.69",
          "2018_publications": "49",
          "2018_porcent_total_publications": "0.09",
          "2017_2018_publications": "-10",
          "2018_downloads": "74074",
          "2018_porcent_total_downloads": 0.07,
          "2018_LAC_downloads": 59662,
          "2018_porcent_total_LAC_downloads": "0.81"
        },
        {
          "department_codes": "Discontinued Departments",
          "all_the_time_publications": 2252,
          "all_the_time_porcent_total_publications": 0.22,
          "all_the_time_downloads": "1454697",
          "all_the_time_porcent_total_downloads": 0.11,
          "all_the_time_LAC_downloads": "792528",
          "all_the_time_porcent_total_LAC_downloads": "0.54",
          "2018_publications": "7",
          "2018_porcent_total_publications": "0.01",
          "2017_2018_publications": "+3",
          "2018_downloads": "5583",
          "2018_porcent_total_downloads": 0.01,
          "2018_LAC_downloads": 2714,
          "2018_porcent_total_LAC_downloads": "0.49"
        },
        {
          "department_codes": "ESG",
          "all_the_time_publications": 171,
          "all_the_time_porcent_total_publications": 0.02,
          "all_the_time_downloads": "203548",
          "all_the_time_porcent_total_downloads": 0.01,
          "all_the_time_LAC_downloads": "93591",
          "all_the_time_porcent_total_LAC_downloads": "0.46",
          "2018_publications": "5",
          "2018_porcent_total_publications": "0.01",
          "2017_2018_publications": "+1",
          "2018_downloads": "21973",
          "2018_porcent_total_downloads": 0.02,
          "2018_LAC_downloads": 19055,
          "2018_porcent_total_LAC_downloads": "0.87"
        },
        {
          "department_codes": "FMP",
          "all_the_time_publications": 10,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "10229",
          "all_the_time_porcent_total_downloads": 0,
          "all_the_time_LAC_downloads": "4575",
          "all_the_time_porcent_total_LAC_downloads": "0.45",
          "2018_publications": "2",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "+2",
          "2018_downloads": "207",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_downloads": 75,
          "2018_porcent_total_LAC_downloads": "0.36"
        },
        {
          "department_codes": "HRD",
          "all_the_time_publications": 2,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "164",
          "all_the_time_porcent_total_downloads": 0,
          "all_the_time_LAC_downloads": "53",
          "all_the_time_porcent_total_LAC_downloads": "0.32",
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "department_codes": "IFD",
          "all_the_time_publications": 983,
          "all_the_time_porcent_total_publications": 0.1,
          "all_the_time_downloads": "2093541",
          "all_the_time_porcent_total_downloads": 0.15,
          "all_the_time_LAC_downloads": "1331387",
          "all_the_time_porcent_total_LAC_downloads": "0.64",
          "2018_publications": "98",
          "2018_porcent_total_publications": "0.19",
          "2017_2018_publications": "+13",
          "2018_downloads": "151007",
          "2018_porcent_total_downloads": 0.14,
          "2018_LAC_downloads": 112298,
          "2018_porcent_total_LAC_downloads": "0.74"
        },
        {
          "department_codes": "INE",
          "all_the_time_publications": 555,
          "all_the_time_porcent_total_publications": 0.05,
          "all_the_time_downloads": "1378205",
          "all_the_time_porcent_total_downloads": 0.1,
          "all_the_time_LAC_downloads": "973777",
          "all_the_time_porcent_total_LAC_downloads": "0.71",
          "2018_publications": "66",
          "2018_porcent_total_publications": "0.13",
          "2017_2018_publications": "+6",
          "2018_downloads": "93222",
          "2018_porcent_total_downloads": 0.09,
          "2018_LAC_downloads": 77386,
          "2018_porcent_total_LAC_downloads": "0.83"
        },
        {
          "department_codes": "INT",
          "all_the_time_publications": 1122,
          "all_the_time_porcent_total_publications": 0.11,
          "all_the_time_downloads": "1029695",
          "all_the_time_porcent_total_downloads": 0.08,
          "all_the_time_LAC_downloads": "607540",
          "all_the_time_porcent_total_LAC_downloads": "0.59",
          "2018_publications": "42",
          "2018_porcent_total_publications": "0.08",
          "2017_2018_publications": "+17",
          "2018_downloads": "120368",
          "2018_porcent_total_downloads": 0.12,
          "2018_LAC_downloads": 98369,
          "2018_porcent_total_LAC_downloads": "0.82"
        },
        {
          "department_codes": "ITE",
          "all_the_time_publications": 3,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "7936",
          "all_the_time_porcent_total_downloads": 0,
          "all_the_time_LAC_downloads": "5781",
          "all_the_time_porcent_total_LAC_downloads": "0.73",
          "2018_publications": "2",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "+2",
          "2018_downloads": "7791",
          "2018_porcent_total_downloads": 0.01,
          "2018_LAC_downloads": 5768,
          "2018_porcent_total_LAC_downloads": "0.74"
        },
        {
          "department_codes": "KIC",
          "all_the_time_publications": 451,
          "all_the_time_porcent_total_publications": 0.04,
          "all_the_time_downloads": "1400816",
          "all_the_time_porcent_total_downloads": 0.1,
          "all_the_time_LAC_downloads": "1000381",
          "all_the_time_porcent_total_LAC_downloads": "0.71",
          "2018_publications": "10",
          "2018_porcent_total_publications": "0.02",
          "2017_2018_publications": "-8",
          "2018_downloads": "81297",
          "2018_porcent_total_downloads": 0.08,
          "2018_LAC_downloads": 45770,
          "2018_porcent_total_LAC_downloads": "0.56"
        },
        {
          "department_codes": "MICI",
          "all_the_time_publications": 12,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "3919",
          "all_the_time_porcent_total_downloads": 0,
          "all_the_time_LAC_downloads": "606",
          "all_the_time_porcent_total_LAC_downloads": "0.15",
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "department_codes": "MIF",
          "all_the_time_publications": 1084,
          "all_the_time_porcent_total_publications": 0.11,
          "all_the_time_downloads": "366180",
          "all_the_time_porcent_total_downloads": 0.03,
          "all_the_time_LAC_downloads": "175405",
          "all_the_time_porcent_total_LAC_downloads": "0.48",
          "2018_publications": "13",
          "2018_porcent_total_publications": "0.02",
          "2017_2018_publications": "-15",
          "2018_downloads": "3929",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_downloads": 1628,
          "2018_porcent_total_LAC_downloads": "0.41"
        },
        {
          "department_codes": "OII",
          "all_the_time_publications": 26,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "5169",
          "all_the_time_porcent_total_downloads": 0,
          "all_the_time_LAC_downloads": "829",
          "all_the_time_porcent_total_LAC_downloads": "0.16",
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "-2",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "department_codes": "ORP",
          "all_the_time_publications": 37,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "41420",
          "all_the_time_porcent_total_downloads": 0,
          "all_the_time_LAC_downloads": "16640",
          "all_the_time_porcent_total_LAC_downloads": "0.4",
          "2018_publications": "1",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "-1",
          "2018_downloads": "2672",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_downloads": 1618,
          "2018_porcent_total_LAC_downloads": "0.61"
        },
        {
          "department_codes": "OVE",
          "all_the_time_publications": 733,
          "all_the_time_porcent_total_publications": 0.07,
          "all_the_time_downloads": "466022",
          "all_the_time_porcent_total_downloads": 0.03,
          "all_the_time_LAC_downloads": "201575",
          "all_the_time_porcent_total_LAC_downloads": "0.43",
          "2018_publications": "30",
          "2018_porcent_total_publications": "0.06",
          "2017_2018_publications": "-22",
          "2018_downloads": "13879",
          "2018_porcent_total_downloads": 0.01,
          "2018_LAC_downloads": 9323,
          "2018_porcent_total_LAC_downloads": "0.67"
        },
        {
          "department_codes": "PRE",
          "all_the_time_publications": 8,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "8246",
          "all_the_time_porcent_total_downloads": 0,
          "all_the_time_LAC_downloads": "2896",
          "all_the_time_porcent_total_LAC_downloads": "0.35",
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "department_codes": "RES",
          "all_the_time_publications": 1288,
          "all_the_time_porcent_total_publications": 0.13,
          "all_the_time_downloads": "1501523",
          "all_the_time_porcent_total_downloads": 0.11,
          "all_the_time_LAC_downloads": "704984",
          "all_the_time_porcent_total_LAC_downloads": "0.47",
          "2018_publications": "34",
          "2018_porcent_total_publications": "0.06",
          "2017_2018_publications": "-21",
          "2018_downloads": "79095",
          "2018_porcent_total_downloads": 0.08,
          "2018_LAC_downloads": 58999,
          "2018_porcent_total_LAC_downloads": "0.75"
        },
        {
          "department_codes": "RMG",
          "all_the_time_publications": 1,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "147",
          "all_the_time_porcent_total_downloads": 0,
          "all_the_time_LAC_downloads": "9",
          "all_the_time_porcent_total_LAC_downloads": "0.06",
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "-1",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "department_codes": "SCL",
          "all_the_time_publications": 817,
          "all_the_time_porcent_total_publications": 0.08,
          "all_the_time_downloads": "2181292",
          "all_the_time_porcent_total_downloads": 0.16,
          "all_the_time_LAC_downloads": "1542743",
          "all_the_time_porcent_total_LAC_downloads": "0.71",
          "2018_publications": "74",
          "2018_porcent_total_publications": "0.14",
          "2017_2018_publications": "-42",
          "2018_downloads": "242419",
          "2018_porcent_total_downloads": 0.23,
          "2018_LAC_downloads": 202383,
          "2018_porcent_total_LAC_downloads": "0.83"
        },
        {
          "department_codes": "SEC",
          "all_the_time_publications": 31,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "8217",
          "all_the_time_porcent_total_downloads": 0,
          "all_the_time_LAC_downloads": "3469",
          "all_the_time_porcent_total_LAC_downloads": "0.42",
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "department_codes": "SPD",
          "all_the_time_publications": 152,
          "all_the_time_porcent_total_publications": 0.01,
          "all_the_time_downloads": "244712",
          "all_the_time_porcent_total_downloads": 0.02,
          "all_the_time_LAC_downloads": "106767",
          "all_the_time_porcent_total_LAC_downloads": "0.44",
          "2018_publications": "29",
          "2018_porcent_total_publications": "0.06",
          "2017_2018_publications": "+10",
          "2018_downloads": "23325",
          "2018_porcent_total_downloads": 0.02,
          "2018_LAC_downloads": 13801,
          "2018_porcent_total_LAC_downloads": "0.59"
        },
        {
          "department_codes": "Strategic Core",
          "all_the_time_publications": 1,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "19721",
          "all_the_time_porcent_total_downloads": 0,
          "all_the_time_LAC_downloads": "16370",
          "all_the_time_porcent_total_LAC_downloads": "0.83",
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "department_codes": "VPC",
          "all_the_time_publications": 31,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "33446",
          "all_the_time_porcent_total_downloads": 0,
          "all_the_time_LAC_downloads": "23990",
          "all_the_time_porcent_total_LAC_downloads": "0.72",
          "2018_publications": "4",
          "2018_porcent_total_publications": "0.01",
          "2017_2018_publications": "+4",
          "2018_downloads": "1274",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_downloads": 769,
          "2018_porcent_total_LAC_downloads": "0.6"
        },
        {
          "department_codes": "VPS",
          "all_the_time_publications": 24,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "97629",
          "all_the_time_porcent_total_downloads": 0.01,
          "all_the_time_LAC_downloads": "73225",
          "all_the_time_porcent_total_LAC_downloads": "0.75",
          "2018_publications": "9",
          "2018_porcent_total_publications": "0.02",
          "2017_2018_publications": "+9",
          "2018_downloads": "47489",
          "2018_porcent_total_downloads": 0.05,
          "2018_LAC_downloads": 38866,
          "2018_porcent_total_LAC_downloads": "0.82"
        }
      ],
    publicationsDivisions: [
        {
          "division_codes": "ATI",
          "all_the_time_publications": 4,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "4359",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "2040",
          "all_the_time_porcent_total_LAC_downloads": 0.47,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "AUG",
          "all_the_time_publications": 1,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "141",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "32",
          "all_the_time_porcent_total_LAC_downloads": 0.23,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "BOG",
          "all_the_time_publications": 4,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "1085",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "172",
          "all_the_time_porcent_total_LAC_downloads": 0.16,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "CAN",
          "all_the_time_publications": 58,
          "all_the_time_porcent_total_publications": 0.01,
          "all_the_time_downloads": "165270",
          "all _the_time_porcent_total_of_downloads": 0.01,
          "all_the_time_LAC_downloads": "125294",
          "all_the_time_porcent_total_LAC_downloads": 0.76,
          "2018_publications": "14",
          "2018_porcent_total_publications": "0.03",
          "2017_2018_publications": "+10",
          "2018_downloads": "33102",
          "2018_porcent_total_downloads": 0.03,
          "2018_LAC_Downloads": 25642,
          "2018_porcent_total_LAC_downloads": "0.77"
        },
        {
          "division_codes": "CAR",
          "all_the_time_publications": 1,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "2232",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "1663",
          "all_the_time_porcent_total_LAC_downloads": 0.75,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "CBH",
          "all_the_time_publications": 1,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "315",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "42",
          "all_the_time_porcent_total_LAC_downloads": 0.13,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "CBL",
          "all_the_time_publications": 3,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "3760",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "937",
          "all_the_time_porcent_total_LAC_downloads": 0.25,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "-1",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "CBO",
          "all_the_time_publications": 2,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "507",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "246",
          "all_the_time_porcent_total_LAC_downloads": 0.49,
          "2018_publications": "2",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "+2",
          "2018_downloads": "507",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 246,
          "2018_porcent_total_LAC_downloads": "0.49"
        },
        {
          "division_codes": "CBR",
          "all_the_time_publications": 1,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "206",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "89",
          "all_the_time_porcent_total_LAC_downloads": 0.43,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "CCB",
          "all_the_time_publications": 149,
          "all_the_time_porcent_total_publications": 0.01,
          "all_the_time_downloads": "234439",
          "all _the_time_porcent_total_of_downloads": 0.02,
          "all_the_time_LAC_downloads": "106184",
          "all_the_time_porcent_total_LAC_downloads": 0.45,
          "2018_publications": "32",
          "2018_porcent_total_publications": "0.06",
          "2017_2018_publications": "+7",
          "2018_downloads": "12777",
          "2018_porcent_total_downloads": 0.01,
          "2018_LAC_Downloads": 5787,
          "2018_porcent_total_LAC_downloads": "0.45"
        },
        {
          "division_codes": "CCH",
          "all_the_time_publications": 18,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "3877",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "2002",
          "all_the_time_porcent_total_LAC_downloads": 0.52,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "CCO",
          "all_the_time_publications": 2,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "1407",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "379",
          "all_the_time_porcent_total_LAC_downloads": 0.27,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "CCS",
          "all_the_time_publications": 44,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "67296",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "40080",
          "all_the_time_porcent_total_LAC_downloads": 0.6,
          "2018_publications": "11",
          "2018_porcent_total_publications": "0.02",
          "2017_2018_publications": "0",
          "2018_downloads": "22966",
          "2018_porcent_total_downloads": 0.02,
          "2018_LAC_Downloads": 17075,
          "2018_porcent_total_LAC_downloads": "0.74"
        },
        {
          "division_codes": "CDR",
          "all_the_time_publications": 3,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "5826",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "4547",
          "all_the_time_porcent_total_LAC_downloads": 0.78,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "CGY",
          "all_the_time_publications": 1,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "868",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "98",
          "all_the_time_porcent_total_LAC_downloads": 0.11,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "CHO",
          "all_the_time_publications": 1,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "1102",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "892",
          "all_the_time_porcent_total_LAC_downloads": 0.81,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "CID",
          "all_the_time_publications": 90,
          "all_the_time_porcent_total_publications": 0.01,
          "all_the_time_downloads": "125646",
          "all _the_time_porcent_total_of_downloads": 0.01,
          "all_the_time_LAC_downloads": "82638",
          "all_the_time_porcent_total_LAC_downloads": 0.66,
          "2018_publications": "20",
          "2018_porcent_total_publications": "0.04",
          "2017_2018_publications": "+12",
          "2018_downloads": "17559",
          "2018_porcent_total_downloads": 0.02,
          "2018_LAC_Downloads": 13949,
          "2018_porcent_total_LAC_downloads": "0.79"
        },
        {
          "division_codes": "CJA",
          "all_the_time_publications": 2,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "1218",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "200",
          "all_the_time_porcent_total_LAC_downloads": 0.16,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "CME",
          "all_the_time_publications": 5,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "6071",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "4692",
          "all_the_time_porcent_total_LAC_downloads": 0.77,
          "2018_publications": "2",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "+2",
          "2018_downloads": "188",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 129,
          "2018_porcent_total_LAC_downloads": "0.69"
        },
        {
          "division_codes": "CMF",
          "all_the_time_publications": 196,
          "all_the_time_porcent_total_publications": 0.02,
          "all_the_time_downloads": "296081",
          "all _the_time_porcent_total_of_downloads": 0.02,
          "all_the_time_LAC_downloads": "170930",
          "all_the_time_porcent_total_LAC_downloads": 0.58,
          "2018_publications": "19",
          "2018_porcent_total_publications": "0.04",
          "2017_2018_publications": "-10",
          "2018_downloads": "26770",
          "2018_porcent_total_downloads": 0.03,
          "2018_LAC_Downloads": 19934,
          "2018_porcent_total_LAC_downloads": "0.74"
        },
        {
          "division_codes": "CMG",
          "all_the_time_publications": 26,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "44707",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "21679",
          "all_the_time_porcent_total_LAC_downloads": 0.48,
          "2018_publications": "3",
          "2018_porcent_total_publications": "0.01",
          "2017_2018_publications": "+3",
          "2018_downloads": "9853",
          "2018_porcent_total_downloads": 0.01,
          "2018_LAC_Downloads": 8803,
          "2018_porcent_total_LAC_downloads": "0.89"
        },
        {
          "division_codes": "CNI",
          "all_the_time_publications": 1,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "392",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "250",
          "all_the_time_porcent_total_LAC_downloads": 0.64,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "-1",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "CPE",
          "all_the_time_publications": 5,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "13364",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "10506",
          "all_the_time_porcent_total_LAC_downloads": 0.79,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "CPR",
          "all_the_time_publications": 1,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "137",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "50",
          "all_the_time_porcent_total_LAC_downloads": 0.36,
          "2018_publications": "1",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "+1",
          "2018_downloads": "137",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 50,
          "2018_porcent_total_LAC_downloads": "0.36"
        },
        {
          "division_codes": "CSC",
          "all_the_time_publications": 32,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "32051",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "22361",
          "all_the_time_porcent_total_LAC_downloads": 0.7,
          "2018_publications": "12",
          "2018_porcent_total_publications": "0.02",
          "2017_2018_publications": "+12",
          "2018_downloads": "2745",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 1272,
          "2018_porcent_total_LAC_downloads": "0.46"
        },
        {
          "division_codes": "CSD",
          "all_the_time_publications": 5,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "17719",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "15172",
          "all_the_time_porcent_total_LAC_downloads": 0.86,
          "2018_publications": "4",
          "2018_porcent_total_publications": "0.01",
          "2017_2018_publications": "+3",
          "2018_downloads": "17169",
          "2018_porcent_total_downloads": 0.02,
          "2018_LAC_Downloads": 15044,
          "2018_porcent_total_LAC_downloads": "0.88"
        },
        {
          "division_codes": "CSO",
          "all_the_time_publications": 66,
          "all_the_time_porcent_total_publications": 0.01,
          "all_the_time_downloads": "147038",
          "all _the_time_porcent_total_of_downloads": 0.01,
          "all_the_time_LAC_downloads": "120751",
          "all_the_time_porcent_total_LAC_downloads": 0.82,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "-7",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "CTI",
          "all_the_time_publications": 187,
          "all_the_time_porcent_total_publications": 0.02,
          "all_the_time_downloads": "371102",
          "all _the_time_porcent_total_of_downloads": 0.03,
          "all_the_time_LAC_downloads": "242111",
          "all_the_time_porcent_total_LAC_downloads": 0.65,
          "2018_publications": "7",
          "2018_porcent_total_publications": "0.01",
          "2017_2018_publications": "-13",
          "2018_downloads": "7327",
          "2018_porcent_total_downloads": 0.01,
          "2018_LAC_Downloads": 5470,
          "2018_porcent_total_LAC_downloads": "0.75"
        },
        {
          "division_codes": "CUR",
          "all_the_time_publications": 1,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "128",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "103",
          "all_the_time_porcent_total_LAC_downloads": 0.8,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "128",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 103,
          "2018_porcent_total_LAC_downloads": "0.8"
        },
        {
          "division_codes": "Discontinued Divisions",
          "all_the_time_publications": "2,252",
          "all_the_time_porcent_total_publications": 0.22,
          "all_the_time_downloads": "1454697",
          "all _the_time_porcent_total_of_downloads": 0.11,
          "all_the_time_LAC_downloads": "792528",
          "all_the_time_porcent_total_LAC_downloads": 0.54,
          "2018_publications": "7",
          "2018_porcent_total_publications": "0.01",
          "2017_2018_publications": "+3",
          "2018_downloads": "5583",
          "2018_porcent_total_downloads": 0.01,
          "2018_LAC_Downloads": 2714,
          "2018_porcent_total_LAC_downloads": "0.49"
        },
        {
          "division_codes": "EDU",
          "all_the_time_publications": 245,
          "all_the_time_porcent_total_publications": 0.02,
          "all_the_time_downloads": "741843",
          "all _the_time_porcent_total_of_downloads": 0.05,
          "all_the_time_LAC_downloads": "575425",
          "all_the_time_porcent_total_LAC_downloads": 0.78,
          "2018_publications": "20",
          "2018_porcent_total_publications": "0.04",
          "2017_2018_publications": "+4",
          "2018_downloads": "52864",
          "2018_porcent_total_downloads": 0.05,
          "2018_LAC_Downloads": 48182,
          "2018_porcent_total_LAC_downloads": "0.91"
        },
        {
          "division_codes": "ENE",
          "all_the_time_publications": 149,
          "all_the_time_porcent_total_publications": 0.01,
          "all_the_time_downloads": "365465",
          "all _the_time_porcent_total_of_downloads": 0.03,
          "all_the_time_LAC_downloads": "222849",
          "all_the_time_porcent_total_LAC_downloads": 0.61,
          "2018_publications": "4",
          "2018_porcent_total_publications": "0.01",
          "2017_2018_publications": "-22",
          "2018_downloads": "12520",
          "2018_porcent_total_downloads": 0.01,
          "2018_LAC_Downloads": 11014,
          "2018_porcent_total_LAC_downloads": "0.88"
        },
        {
          "division_codes": "ESG",
          "all_the_time_publications": 171,
          "all_the_time_porcent_total_publications": 0.02,
          "all_the_time_downloads": "203548",
          "all _the_time_porcent_total_of_downloads": 0.01,
          "all_the_time_LAC_downloads": "93591",
          "all_the_time_porcent_total_LAC_downloads": 0.46,
          "2018_publications": "5",
          "2018_porcent_total_publications": "0.01",
          "2017_2018_publications": "+1",
          "2018_downloads": "21973",
          "2018_porcent_total_downloads": 0.02,
          "2018_LAC_Downloads": 19055,
          "2018_porcent_total_LAC_downloads": "0.87"
        },
        {
          "division_codes": "EUR",
          "all_the_time_publications": 5,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "4664",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "1379",
          "all_the_time_porcent_total_LAC_downloads": 0.3,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "FHL",
          "all_the_time_publications": 30,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "11790",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "6924",
          "all_the_time_porcent_total_LAC_downloads": 0.59,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "-3",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "FMM",
          "all_the_time_publications": 193,
          "all_the_time_porcent_total_publications": 0.02,
          "all_the_time_downloads": "500416",
          "all _the_time_porcent_total_of_downloads": 0.04,
          "all_the_time_LAC_downloads": "319740",
          "all_the_time_porcent_total_LAC_downloads": 0.64,
          "2018_publications": "23",
          "2018_porcent_total_publications": "0.04",
          "2017_2018_publications": "+10",
          "2018_downloads": "29137",
          "2018_porcent_total_downloads": 0.03,
          "2018_LAC_Downloads": 19920,
          "2018_porcent_total_LAC_downloads": "0.68"
        },
        {
          "division_codes": "FMP",
          "all_the_time_publications": 10,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "10229",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "4575",
          "all_the_time_porcent_total_LAC_downloads": 0.45,
          "2018_publications": "2",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "+2",
          "2018_downloads": "207",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 75,
          "2018_porcent_total_LAC_downloads": "0.36"
        },
        {
          "division_codes": "GCM",
          "all_the_time_publications": 21,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "4349",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "1248",
          "all_the_time_porcent_total_LAC_downloads": 0.29,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "GDI",
          "all_the_time_publications": 67,
          "all_the_time_porcent_total_publications": 0.01,
          "all_the_time_downloads": "60284",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "39839",
          "all_the_time_porcent_total_LAC_downloads": 0.66,
          "2018_publications": "6",
          "2018_porcent_total_publications": "0.01",
          "2017_2018_publications": "-13",
          "2018_downloads": "1505",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 627,
          "2018_porcent_total_LAC_downloads": "0.42"
        },
        {
          "division_codes": "HRD",
          "all_the_time_publications": 2,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "164",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "53",
          "all_the_time_porcent_total_LAC_downloads": 0.32,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "HUD",
          "all_the_time_publications": 76,
          "all_the_time_porcent_total_publications": 0.01,
          "all_the_time_downloads": "378294",
          "all _the_time_porcent_total_of_downloads": 0.03,
          "all_the_time_LAC_downloads": "266852",
          "all_the_time_porcent_total_LAC_downloads": 0.71,
          "2018_publications": "9",
          "2018_porcent_total_publications": "0.02",
          "2017_2018_publications": "+1",
          "2018_downloads": "15264",
          "2018_porcent_total_downloads": 0.01,
          "2018_LAC_Downloads": 12623,
          "2018_porcent_total_LAC_downloads": "0.83"
        },
        {
          "division_codes": "ICD",
          "all_the_time_publications": 1,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "4563",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "4125",
          "all_the_time_porcent_total_LAC_downloads": 0.9,
          "2018_publications": "1",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "+1",
          "2018_downloads": "4563",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 4125,
          "2018_porcent_total_LAC_downloads": "0.9"
        },
        {
          "division_codes": "ICS",
          "all_the_time_publications": 330,
          "all_the_time_porcent_total_publications": 0.03,
          "all_the_time_downloads": "790453",
          "all _the_time_porcent_total_of_downloads": 0.06,
          "all_the_time_LAC_downloads": "525009",
          "all_the_time_porcent_total_LAC_downloads": 0.66,
          "2018_publications": "48",
          "2018_porcent_total_publications": "0.09",
          "2017_2018_publications": "+28",
          "2018_downloads": "87714",
          "2018_porcent_total_downloads": 0.08,
          "2018_LAC_Downloads": 66957,
          "2018_porcent_total_LAC_downloads": "0.76"
        },
        {
          "division_codes": "IFD",
          "all_the_time_publications": 78,
          "all_the_time_porcent_total_publications": 0.01,
          "all_the_time_downloads": "135489",
          "all _the_time_porcent_total_of_downloads": 0.01,
          "all_the_time_LAC_downloads": "73597",
          "all_the_time_porcent_total_LAC_downloads": 0.54,
          "2018_publications": "1",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "-3",
          "2018_downloads": "59",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 17,
          "2018_porcent_total_LAC_downloads": "0.29"
        },
        {
          "division_codes": "INE",
          "all_the_time_publications": 63,
          "all_the_time_porcent_total_publications": 0.01,
          "all_the_time_downloads": "149465",
          "all _the_time_porcent_total_of_downloads": 0.01,
          "all_the_time_LAC_downloads": "86887",
          "all_the_time_porcent_total_LAC_downloads": 0.58,
          "2018_publications": "17",
          "2018_porcent_total_publications": "0.03",
          "2017_2018_publications": "+7",
          "2018_downloads": "7666",
          "2018_porcent_total_downloads": 0.01,
          "2018_LAC_Downloads": 4600,
          "2018_porcent_total_LAC_downloads": "0.6"
        },
        {
          "division_codes": "INL",
          "all_the_time_publications": 502,
          "all_the_time_porcent_total_publications": 0.05,
          "all_the_time_downloads": "454087",
          "all _the_time_porcent_total_of_downloads": 0.03,
          "all_the_time_LAC_downloads": "318719",
          "all_the_time_porcent_total_LAC_downloads": 0.7,
          "2018_publications": "14",
          "2018_porcent_total_publications": "0.03",
          "2017_2018_publications": "-3",
          "2018_downloads": "90165",
          "2018_porcent_total_downloads": 0.09,
          "2018_LAC_Downloads": 81799,
          "2018_porcent_total_LAC_downloads": "0.91"
        },
        {
          "division_codes": "INT",
          "all_the_time_publications": 621,
          "all_the_time_porcent_total_publications": 0.06,
          "all_the_time_downloads": "575608",
          "all _the_time_porcent_total_of_downloads": 0.04,
          "all_the_time_LAC_downloads": "288821",
          "all_the_time_porcent_total_LAC_downloads": 0.5,
          "2018_publications": "28",
          "2018_porcent_total_publications": "0.05",
          "2017_2018_publications": "+20",
          "2018_downloads": "30203",
          "2018_porcent_total_downloads": 0.03,
          "2018_LAC_Downloads": 16570,
          "2018_porcent_total_LAC_downloads": "0.55"
        },
        {
          "division_codes": "ITE",
          "all_the_time_publications": 3,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "7936",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "5781",
          "all_the_time_porcent_total_LAC_downloads": 0.73,
          "2018_publications": "2",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "+2",
          "2018_downloads": "7791",
          "2018_porcent_total_downloads": 0.01,
          "2018_LAC_Downloads": 5768,
          "2018_porcent_total_LAC_downloads": "0.74"
        },
        {
          "division_codes": "KIC",
          "all_the_time_publications": 170,
          "all_the_time_porcent_total_publications": 0.02,
          "all_the_time_downloads": "932852",
          "all _the_time_porcent_total_of_downloads": 0.07,
          "all_the_time_LAC_downloads": "650768",
          "all_the_time_porcent_total_LAC_downloads": 0.7,
          "2018_publications": "4",
          "2018_porcent_total_publications": "0.01",
          "2017_2018_publications": "-4",
          "2018_downloads": "38505",
          "2018_porcent_total_downloads": 0.04,
          "2018_LAC_Downloads": 5963,
          "2018_porcent_total_LAC_downloads": "0.15"
        },
        {
          "division_codes": "KNM",
          "all_the_time_publications": 23,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "21359",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "13965",
          "all_the_time_porcent_total_LAC_downloads": 0.65,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "LMK",
          "all_the_time_publications": 164,
          "all_the_time_porcent_total_publications": 0.02,
          "all_the_time_downloads": "393568",
          "all _the_time_porcent_total_of_downloads": 0.03,
          "all_the_time_LAC_downloads": "265139",
          "all_the_time_porcent_total_LAC_downloads": 0.67,
          "2018_publications": "14",
          "2018_porcent_total_publications": "0.03",
          "2017_2018_publications": "-15",
          "2018_downloads": "75788",
          "2018_porcent_total_downloads": 0.07,
          "2018_LAC_Downloads": 65248,
          "2018_porcent_total_LAC_downloads": "0.86"
        },
        {
          "division_codes": "MICI",
          "all_the_time_publications": 12,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "3919",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "606",
          "all_the_time_porcent_total_LAC_downloads": 0.15,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "MIF",
          "all_the_time_publications": "1,084",
          "all_the_time_porcent_total_publications": 0.11,
          "all_the_time_downloads": "366180",
          "all _the_time_porcent_total_of_downloads": 0.03,
          "all_the_time_LAC_downloads": "175405",
          "all_the_time_porcent_total_LAC_downloads": 0.48,
          "2018_publications": "13",
          "2018_porcent_total_publications": "0.02",
          "2017_2018_publications": "-15",
          "2018_downloads": "3929",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 1628,
          "2018_porcent_total_LAC_downloads": "0.41"
        },
        {
          "division_codes": "OII",
          "all_the_time_publications": 26,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "5169",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "829",
          "all_the_time_porcent_total_LAC_downloads": 0.16,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "-2",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "ORP",
          "all_the_time_publications": 12,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "32407",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "14013",
          "all_the_time_porcent_total_LAC_downloads": 0.43,
          "2018_publications": "1",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "-1",
          "2018_downloads": "2672",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 1618,
          "2018_porcent_total_LAC_downloads": "0.61"
        },
        {
          "division_codes": "OVE",
          "all_the_time_publications": 733,
          "all_the_time_porcent_total_publications": 0.07,
          "all_the_time_downloads": "466022",
          "all _the_time_porcent_total_of_downloads": 0.03,
          "all_the_time_LAC_downloads": "201575",
          "all_the_time_porcent_total_LAC_downloads": 0.43,
          "2018_publications": "30",
          "2018_porcent_total_publications": "0.06",
          "2017_2018_publications": "-22",
          "2018_downloads": "13879",
          "2018_porcent_total_downloads": 0.01,
          "2018_LAC_Downloads": 9323,
          "2018_porcent_total_LAC_downloads": "0.67"
        },
        {
          "division_codes": "PCY",
          "all_the_time_publications": 2,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "255",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "63",
          "all_the_time_porcent_total_LAC_downloads": 0.25,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "PRE",
          "all_the_time_publications": 6,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "7991",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "2833",
          "all_the_time_porcent_total_LAC_downloads": 0.35,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "PRO",
          "all_the_time_publications": 1,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "143",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "8",
          "all_the_time_porcent_total_LAC_downloads": 0.06,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "RES",
          "all_the_time_publications": "1,288",
          "all_the_time_porcent_total_publications": 0.13,
          "all_the_time_downloads": "1501523",
          "all _the_time_porcent_total_of_downloads": 0.11,
          "all_the_time_LAC_downloads": "704984",
          "all_the_time_porcent_total_LAC_downloads": 0.47,
          "2018_publications": "34",
          "2018_porcent_total_publications": "0.06",
          "2017_2018_publications": "-21",
          "2018_downloads": "79095",
          "2018_porcent_total_downloads": 0.08,
          "2018_LAC_Downloads": 58999,
          "2018_porcent_total_LAC_downloads": "0.75"
        },
        {
          "division_codes": "RMG",
          "all_the_time_publications": 1,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "147",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "9",
          "all_the_time_porcent_total_LAC_downloads": 0.06,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "-1",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "RND",
          "all_the_time_publications": 124,
          "all_the_time_porcent_total_publications": 0.01,
          "all_the_time_downloads": "95657",
          "all _the_time_porcent_total_of_downloads": 0.01,
          "all_the_time_LAC_downloads": "62616",
          "all_the_time_porcent_total_LAC_downloads": 0.65,
          "2018_publications": "25",
          "2018_porcent_total_publications": "0.05",
          "2017_2018_publications": "-14",
          "2018_downloads": "18675",
          "2018_porcent_total_downloads": 0.02,
          "2018_LAC_Downloads": 14920,
          "2018_porcent_total_LAC_downloads": "0.8"
        },
        {
          "division_codes": "SCL",
          "all_the_time_publications": 53,
          "all_the_time_porcent_total_publications": 0.01,
          "all_the_time_downloads": "119949",
          "all _the_time_porcent_total_of_downloads": 0.01,
          "all_the_time_LAC_downloads": "77398",
          "all_the_time_porcent_total_LAC_downloads": 0.65,
          "2018_publications": "9",
          "2018_porcent_total_publications": "0.02",
          "2017_2018_publications": "-1",
          "2018_downloads": "48822",
          "2018_porcent_total_downloads": 0.05,
          "2018_LAC_Downloads": 42244,
          "2018_porcent_total_LAC_downloads": "0.87"
        },
        {
          "division_codes": "SDI",
          "all_the_time_publications": 134,
          "all_the_time_porcent_total_publications": 0.01,
          "all_the_time_downloads": "210131",
          "all _the_time_porcent_total_of_downloads": 0.02,
          "all_the_time_LAC_downloads": "155290",
          "all_the_time_porcent_total_LAC_downloads": 0.74,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "SDV",
          "all_the_time_publications": 20,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "43721",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "5970",
          "all_the_time_porcent_total_LAC_downloads": 0.14,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "-1",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "SEC",
          "all_the_time_publications": 26,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "3715",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "1421",
          "all_the_time_porcent_total_LAC_downloads": 0.38,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "SMO",
          "all_the_time_publications": 2,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "547",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "128",
          "all_the_time_porcent_total_LAC_downloads": 0.23,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "SPD",
          "all_the_time_publications": 130,
          "all_the_time_porcent_total_publications": 0.01,
          "all_the_time_downloads": "200444",
          "all _the_time_porcent_total_of_downloads": 0.01,
          "all_the_time_LAC_downloads": "100669",
          "all_the_time_porcent_total_LAC_downloads": 0.5,
          "2018_publications": "29",
          "2018_porcent_total_publications": "0.06",
          "2017_2018_publications": "+11",
          "2018_downloads": "23325",
          "2018_porcent_total_downloads": 0.02,
          "2018_LAC_Downloads": 13801,
          "2018_porcent_total_LAC_downloads": "0.59"
        },
        {
          "division_codes": "SPH",
          "all_the_time_publications": 289,
          "all_the_time_porcent_total_publications": 0.03,
          "all_the_time_downloads": "865648",
          "all _the_time_porcent_total_of_downloads": 0.06,
          "all_the_time_LAC_downloads": "584942",
          "all_the_time_porcent_total_LAC_downloads": 0.68,
          "2018_publications": "25",
          "2018_porcent_total_publications": "0.05",
          "2017_2018_publications": "-18",
          "2018_downloads": "63440",
          "2018_porcent_total_downloads": 0.06,
          "2018_LAC_Downloads": 46082,
          "2018_porcent_total_LAC_downloads": "0.73"
        },
        {
          "division_codes": "Strategic Core",
          "all_the_time_publications": 1,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "19721",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "16370",
          "all_the_time_porcent_total_LAC_downloads": 0.83,
          "2018_publications": "0",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "0",
          "2018_downloads": "0",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 0,
          "2018_porcent_total_LAC_downloads": "0"
        },
        {
          "division_codes": "TSP",
          "all_the_time_publications": 171,
          "all_the_time_porcent_total_publications": 0.02,
          "all_the_time_downloads": "427170",
          "all _the_time_porcent_total_of_downloads": 0.03,
          "all_the_time_LAC_downloads": "333593",
          "all_the_time_porcent_total_LAC_downloads": 0.78,
          "2018_publications": "16",
          "2018_porcent_total_publications": "0.03",
          "2017_2018_publications": "+8",
          "2018_downloads": "12584",
          "2018_porcent_total_downloads": 0.01,
          "2018_LAC_Downloads": 9001,
          "2018_porcent_total_LAC_downloads": "0.72"
        },
        {
          "division_codes": "UCC",
          "all_the_time_publications": 2,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "28376",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "26879",
          "all_the_time_porcent_total_LAC_downloads": 0.95,
          "2018_publications": "2",
          "2018_porcent_total_publications": "0",
          "2017_2018_publications": "+2",
          "2018_downloads": "28376",
          "2018_porcent_total_downloads": 0.03,
          "2018_LAC_Downloads": 26879,
          "2018_porcent_total_LAC_downloads": "0.95"
        },
        {
          "division_codes": "VPC",
          "all_the_time_publications": 31,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "33446",
          "all _the_time_porcent_total_of_downloads": 0,
          "all_the_time_LAC_downloads": "23990",
          "all_the_time_porcent_total_LAC_downloads": 0.72,
          "2018_publications": "4",
          "2018_porcent_total_publications": "0.01",
          "2017_2018_publications": "+4",
          "2018_downloads": "1274",
          "2018_porcent_total_downloads": 0,
          "2018_LAC_Downloads": 769,
          "2018_porcent_total_LAC_downloads": "0.6"
        },
        {
          "division_codes": "VPS",
          "all_the_time_publications": 24,
          "all_the_time_porcent_total_publications": 0,
          "all_the_time_downloads": "97629",
          "all _the_time_porcent_total_of_downloads": 0.01,
          "all_the_time_LAC_downloads": "73225",
          "all_the_time_porcent_total_LAC_downloads": 0.75,
          "2018_publications": "9",
          "2018_porcent_total_publications": "0.02",
          "2017_2018_publications": "+9",
          "2018_downloads": "47489",
          "2018_porcent_total_downloads": 0.05,
          "2018_LAC_Downloads": 38866,
          "2018_porcent_total_LAC_downloads": "0.82"
        },
        {
          "division_codes": "WSA",
          "all_the_time_publications": 173,
          "all_the_time_porcent_total_publications": 0.02,
          "all_the_time_downloads": "436105",
          "all _the_time_porcent_total_of_downloads": 0.03,
          "all_the_time_LAC_downloads": "330448",
          "all_the_time_porcent_total_LAC_downloads": 0.76,
          "2018_publications": "30",
          "2018_porcent_total_publications": "0.06",
          "2017_2018_publications": "+14",
          "2018_downloads": "60452",
          "2018_porcent_total_downloads": 0.06,
          "2018_LAC_Downloads": 52771,
          "2018_porcent_total_LAC_downloads": "0.87"
        }
      ],
    publicationsIDB: [{
        "json_featuretype": "NewFeatureType",
        "2018_publications": "525",
        "2018_porcent_total_publications": "1",
        "2017_2018_publications": -38,
        "2018_downloads": "1043000",
        "2018_porcent_total_downloads": "1",
        "2018_porcent_total_LAC_downloads": "0.765146692233941",
        "all_the_time_publications": 10226,
        "all_the_time_downloads": 13106769,
        "all_the_time_porcent_total_LAC_downloads": 0.614829787570072,
        "xlsx_row_id": 2
    }]
};