var codeIndicatorsArrays = {
    indicatorsDepartments: [
        {
            "json_featuretype": "Sheet 1",
            "all_the_time_pageviews": 1977,
            "all_the_time_porcent_total_pageviews": "0.0571106681688188",
            "department_codes": "IFD",
            "2018_code": 2,
            "porcent_total_code": "0.4",
            "2018_pageviews": "845",
            "2018_porcent_total_pageviews": "0.330983157070114",
            "porcent_total_lac": "0.682840236686391",
            "all_the_time_code": 3,
            "xlsx_row_id": 2
        },
        {
            "json_featuretype": "Sheet 1",
            "all_the_time_pageviews": 7896,
            "all_the_time_porcent_total_pageviews": "0.228096022185631",
            "department_codes": "INE",
            "2018_code": 0,
            "porcent_total_code": "0",
            "2018_pageviews": "0",
            "2018_porcent_total_pageviews": "0",
            "porcent_total_lac": "0",
            "all_the_time_code": 2,
            "xlsx_row_id": 3
        },
        {
            "json_featuretype": "Sheet 1",
            "all_the_time_pageviews": 12671,
            "all_the_time_porcent_total_pageviews": "0.366034029523067",
            "department_codes": "KIC",
            "2018_code": 2,
            "porcent_total_code": "0.4",
            "2018_pageviews": "1332",
            "2018_porcent_total_pageviews": "0.521739130434783",
            "porcent_total_lac": "0.722972972972973",
            "all_the_time_code": 11,
            "xlsx_row_id": 4
        },
        {
            "json_featuretype": "Sheet 1",
            "all_the_time_pageviews": 2171,
            "all_the_time_porcent_total_pageviews": "0.0627148510847272",
            "department_codes": "MIF",
            "2018_code": 0,
            "porcent_total_code": "0",
            "2018_pageviews": "0",
            "2018_porcent_total_pageviews": "0",
            "porcent_total_lac": "0",
            "all_the_time_code": 2,
            "xlsx_row_id": 5
        },
        {
            "json_featuretype": "Sheet 1",
            "all_the_time_pageviews": 381,
            "all_the_time_porcent_total_pageviews": "0.0110061530461912",
            "department_codes": "SCL",
            "2018_code": 1,
            "porcent_total_code": "0.2",
            "2018_pageviews": "376",
            "2018_porcent_total_pageviews": "0.147277712495104",
            "porcent_total_lac": "0.664893617021277",
            "all_the_time_code": 1,
            "xlsx_row_id": 6
        },
        {
            "json_featuretype": "Sheet 1",
            "all_the_time_pageviews": 3881,
            "all_the_time_porcent_total_pageviews": "0.112112545858971",
            "department_codes": "SPD",
            "all_the_time_code": 1,
            "2018_code": 0,
            "porcent_total_code": "0",
            "2018_pageviews": "0",
            "2018_porcent_total_pageviews": "0",
            "porcent_total_lac": "0",
            "all_the_time_code": 1,
            "xlsx_row_id": 7
        }
    ],
    indicatorsDivisions: [
        {
            "json_featuretype": "Sheet 1",
            "all_the_time_code": 2,
            "all_the_time_pageviews": 872,
            "all_the_time_porcent_total_pageviews": "0,0252",
            "2018_code": 2,
            "porcent_total_code": "0.4",
            "2018_pageviews": "845",
            "2018_porcent_total_pageviews": "0.330983157070114",
            "porcent_total_lac": "0.682840236686391",
            "division_codes": "FMM",
            "xlsx_row_id": 2
        },
        {
            "json_featuretype": "Sheet 1",
            "2018_code": 0,
            "porcent_total_code": "0",
            "2018_pageviews": "0",
            "2018_porcent_total_pageviews": "0",
            "porcent_total_lac": "0",
            "division_codes": "ICS",
            "xlsx_row_id": 3
        },
        {
            "json_featuretype": "Sheet 1",
            "all_the_time_code": 1,
            "all_the_time_pageviews": 875,
            "all_the_time_porcent_total_pageviews": "0,0253",
            "2018_code": 0,
            "porcent_total_code": "0",
            "2018_pageviews": "0",
            "2018_porcent_total_pageviews": "0",
            "porcent_total_lac": "0",
            "division_codes": "ISU",
            "xlsx_row_id": 4
        },
        {
            "json_featuretype": "Sheet 1",
            "all_the_time_code": 1,
            "all_the_time_pageviews": 838,
            "all_the_time_porcent_total_pageviews": "0,0242",
            "2018_code": 0,
            "porcent_total_code": "0",
            "2018_pageviews": "0",
            "2018_porcent_total_pageviews": "0",
            "porcent_total_lac": "0",
            "division_codes": "KIC",
            "xlsx_row_id": 5
        },
        {
            "json_featuretype": "Sheet 1",
            "all_the_time_code": 9,
            "all_the_time_pageviews": 10958,
            "all_the_time_porcent_total_pageviews": "0,3165",
            "2018_code": 2,
            "porcent_total_code": "0.4",
            "2018_pageviews": "1332",
            "2018_porcent_total_pageviews": "0.521739130434783",
            "porcent_total_lac": "0.722972972972973",
            "division_codes": "KLD",
            "xlsx_row_id": 6
        },
        {
            "json_featuretype": "Sheet 1",
            "all_the_time_code": 2,
            "all_the_time_pageviews": 2171,
            "all_the_time_porcent_total_pageviews": "0,0627",
            "2018_code": 0,
            "porcent_total_code": "0",
            "2018_pageviews": "0",
            "2018_porcent_total_pageviews": "0",
            "porcent_total_lac": "0",
            "division_codes": "MIF",
            "xlsx_row_id": 7
        },
        {
            "json_featuretype": "Sheet 1",
            "all_the_time_code": 1,
            "all_the_time_pageviews": 3881,
            "all_the_time_porcent_total_pageviews": "0,1121",
            "2018_code": 0,
            "porcent_total_code": "0",
            "2018_pageviews": "0",
            "2018_porcent_total_pageviews": "0",
            "porcent_total_lac": "0",
            "division_codes": "SPD",
            "xlsx_row_id": 8
        },
        {
            "json_featuretype": "Sheet 1",
            "all_the_time_code": 1,
            "all_the_time_pageviews": 381,
            "all_the_time_porcent_total_pageviews": "0,011",
            "2018_code": 1,
            "porcent_total_code": "0.2",
            "2018_pageviews": "376",
            "2018_porcent_total_pageviews": "0.147277712495104",
            "porcent_total_lac": "0.664893617021277",
            "division_codes": "SPH",
            "xlsx_row_id": 9
        },
        {
            "json_featuretype": "Sheet 1",
            "all_the_time_code": 2,
            "all_the_time_pageviews": 7896,
            "all_the_time_porcent_total_pageviews": "0,2281",
            "2018_code": 0,
            "porcent_total_code": "0",
            "2018_pageviews": "0",
            "2018_porcent_total_pageviews": "0",
            "porcent_total_lac": "0",
            "division_codes": "WSA",
            "xlsx_row_id": 10
        }
    ],
    indicatorsIDB: [
        {
        "json_featuretype": "Sheet 1",
        "all_the_time_code": 20,
        "all_the_time_pageviews": "34617",
        "all_the_time_porcent_total_pageviews": "1",
        "2018_code": 5,
        "porcent_total_code": "1",
        "2018_pageviews": "2553",
        "2018_porcent_total_pageviews": "1",
        "porcent_total_lac": "0.701135918527223",
        "xlsx_row_id": 2
    }]
};